eval_page/app/views/auth.py
from flask import Blueprint,render_template,url_for, flash, request,session,g
from werkzeug.security import generate_password_hash,check_password_hash
from werkzeug.utils import redirect

from app import db
from ..forms import SignupForm, UserLoginForm, UsermodifyForm
from ..views.evaluate import login_required
from ..models import User
import logging

bp = Blueprint('auth', __name__, url_prefix='/')

@bp.before_app_request
def load_logged_in_user():
    user = session.get('user')
    if user is None:
        g.user = None
    else:
        g.user = User.query.get(user)

@bp.route('/')
def index():
    return render_template('./index.html')

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(userID=form.userID.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.userPasswd, form.userPasswd.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user'] = user.userID
            flash('로그인 성공!!')
            return redirect(url_for('auth.index'))
        flash(error)
    return render_template('page/login.html', form=form)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('auth.index'))

@bp.route('/delete')
@login_required
def delete():
    u = User.query.get_or_404(g.user.userID)
    if g.user == None:
        flash('삭제권한이 없습니다')
        return redirect(url_for('auth.index'))
    db.session.delete(u)
    db.session.commit()
    return redirect(url_for('auth.index'))

@bp.route('/user_update/',methods=('GET','POST'))
@login_required
def user_update():
    form = UsermodifyForm()
    if request.method == 'POST':
            if form.validate_on_submit():
                user = User.query.get(g.user.userID)
                user.userPasswd=generate_password_hash(form.userPasswd.data)
                user.userName=form.userName.data
                user.userSex=form.userSex.data
                db.session.commit()
                flash('회원 정보 수정 완료!!!!')
                return redirect(url_for('auth.index'))
            else:
                flash('수정 에러!')
    return render_template('page/userinfo.html', form=form)

@bp.route('/signup/',methods=('GET','POST'))
def signup():
    form = SignupForm()

    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(userID=form.userID.data).first()
        if not user:
            user = User(userID=form.userID.data,
                        userPasswd=generate_password_hash(form.userPasswd.data),
                        userName=form.userName.data,
                        userSex=form.userSex.data)
            db.session.add(user)
            db.session.commit()
            flash('회원가입 성공!!')
            return redirect(url_for('auth.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    
    return render_template('page/signup.html',form=form)

eval_page/app/templates/page/login.html

<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
			
			<!-- Base css -->
			<link rel="stylesheet" href="{{url_for('static',filename='css/normalize.css')}}">
			<link rel="stylesheet" href="{{url_for('static',filename='css/reset.css')}}"> 
			
			<!-- page css -->
			<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
			<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
			

			<title>이클립스 개인 페이지</title>
	</head>
	<body>
		<div id="wrap">
			<div id="header">
                {% include 'header.html' %}
			</div>
			<!-- header -->
			<div id="contents-log">
				<div id="cont-nav">
					<div class="container">
						{% include 'nav.html' %}
					</div>
				</div>
			
				<div id="cont-log">
					<form action="{{url_for('auth.login')}}" id="login-form" method="POST">
						{{ form.csrf_token }}
						{% include "form_errors.html" %}
	                    <label class="legend">아이디</label>
	                    <input name="userID" type="text" value="{{ form.userID.data or '' }}" required>
	                    <label class="legend">패스워드</label> 
	                    <input name="userPasswd" type="password" value="{{ form.userPasswd.data or '' }}" required> 
	                    <input type="submit" name="key" value="login">
	                    <a class="legend" style="float:right;" href="{{url_for('auth.signup')}}">회원가입</a>
       			  </form>
				</div>
			</div>	
			<!-- contents -->
			<div id="footer">
                {% include 'footer.html' %}
			</div>
		</div>
		<!-- wrap -->
	</body>
</html>

eval_page/app/templates/page/signup.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
			
			<!-- Base css -->
			<link rel="stylesheet" href="{{url_for('static',filename='css/normalize.css')}}">
			<link rel="stylesheet" href="{{url_for('static',filename='css/reset.css')}}"> 
			
			<!-- page css -->
			<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
			<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">

			<title>이클립스 개인 페이지</title>
	</head>
	<body>
		<div id="wrap">
			<div id="header">
                {% include 'header.html' %}
			</div>
			<!-- header -->
			<div id="contents-sign">
				<div id="cont-nav">
					{% include 'nav.html' %}
				</div>
				<div id="sign">
		        <br><br>
		        
		        <div style="text-align:center;">
		        	<font size="6" color="gray">회원가입</font>
		        </div>
		        <br><br>
		        <form action="{{url_for('auth.signup')}}" method="POST">
					{{ form.csrf_token }}
					{% include "form_errors.html" %}
		            <table class="sign-table">
		                <tr>
		                    <td id="title">아이디</td> 
		                    <td>
		                        <input type="text" name="userID" value="{{ form.userID.data or '' }}"maxlength="20" required> 
		                    </td>
		                </tr>
		                        
		                <tr>
		                    <td id="title">비밀번호</td> 
		                    <td>
		                        <input type="password" name="userPasswd" value="{{ form.userPasswd.data or '' }}"maxlength="15" required>
		                    </td>
		                </tr>
		                    
		                <tr>
		                    <td id="title">이름</td>
		                    <td>
		                        <input type="text" name="userName" maxlength="40" value="{{ form.userName.data or '' }}" required>
		                    </td>
		                </tr>
		                    
		                <tr>
		                    <td id="title">성별</td>
		                    <td>
		                        <input type="radio" name="userSex" value="남" checked>남
		                        <input type="radio" name="userSex" value="여" checked>여
		                    </td>
		                </tr>
		            </table>
		            <br>
		             
		             <div class="reset_sign" style="text-align:center;">
			           	 <input type="submit" name="key" value="ok"/>
			           	 <input type="reset" value="cancel">
		            </div>
		        </form>
		   		</div>
			</div>
			<!-- contents -->
			<div id="footer">
                {% include 'footer.html' %}
			</div>
		</div>	
		<!-- wrap -->
	</body>
</html>

eval_page/app/templates/page/userinfo.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">

    <!-- Base css -->
    <link rel="stylesheet" href="{{url_for('static',filename='css/normalize.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/reset.css')}}">

    <!-- page css -->
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">

    <title>이클립스 개인 페이지</title>
</head>

<body>
    <div id="wrap">
        <div id="header">
            {% include 'header.html' %}
        </div>
        <!-- header -->
        <div id="contents-sign">
            <div id="cont-nav">
                {% include 'nav.html' %}
            </div>
            <div id="sign">
                <br><br>

                <div style="text-align:center;">
                    <font size="6" color="gray">회원정보 수정</font>
                </div>
                <br><br>
                <form action="{{url_for('auth.user_update')}}" method="POST">
                    {{ form.hidden_tag() }} {% include "form_errors.html" %}
                    <table class="sign-table">
                        <tr>
                            <td id="title">아이디</td>
                            <td>
                                <input type="text" name="userID" maxlength="20" value="{{g.user.userID}}" disabled="disabled" required>
                            </td>
                        </tr>

                        <tr>
                            <td id="title">비밀번호</td>
                            <td>
                                <input type="password" name="userPasswd" value="" maxlength="15" required>
                            </td>
                        </tr>

                        <tr>
                            <td id="title">이름</td>
                            <td>
                                <input type="text" name="userName" maxlength="40" value="{{g.user.userName}}">
                            </td>
                        </tr>

                        <tr>
                            <td id="title">성별</td>
                            <td>
                                <input type="radio" name="userSex" value="남" checked>남
                                <input type="radio" name="userSex" value="여" checked>여
                            </td>
                        </tr>
                    </table>
                    <br>

                    <div class="reset_sign" style="text-align:center;">
                        <input type="submit" name="key" value="ok" />
                        <a href="{{url_for('auth.index')}}">취소</a>
                    </div>
                    <div><a href="{{url_for('auth.delete')}}" style="float: right;">회원 탈퇴</div>
                </form>
            </div>
        </div>
        <!-- contents -->
        <div id="footer">
            {% include 'footer.html' %}
        </div>
    </div>
    <!-- wrap -->
</body>

</html>