eval_page/app/views/evaluate.py
from flask import Blueprint,render_template,url_for, flash, request,session,g
from werkzeug.security import generate_password_hash,check_password_hash
from werkzeug.utils import redirect
import functools
from app import db
from ..forms import SignupForm, UserLoginForm, UsermodifyForm,RegistForm
from ..models import User,Evaluate
import logging

bp = Blueprint('evaluate', __name__, url_prefix='/evaluate')

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

@bp.before_app_request
def load_logged_in_user():
    user = session.get('user')
    if user is None:
        g.user = None
    else:
        g.user = User.query.get(user)


@bp.route('/')
def evaluate():
    page = request.args.get('page', type=int, default=1)
    list_ = Evaluate.query.order_by(Evaluate.evalID.desc())
    list_ = list_.paginate(page, per_page=5)
    return render_template('evaluate/evaluation.html',list_=list_)

@bp.route('/list/')
def _list():
    # 입력 파라미터
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    
     # 조회
    question_list = Evaluate.query.order_by(Evaluate.evalID.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        question_list = question_list.filter(Evaluate.content_title.ilike(search) |  # 제목
                    Evaluate.eval_contents.ilike(search) |  # 내용
                    Evaluate.writer.ilike(search) |  # 작성자
                    Evaluate.lec_name.ilike(search) |  # 강의명
                    Evaluate.pro_name.ilike(search)  # 교수명
                    ) \
            .distinct()

    # 페이징
    question_list = question_list.paginate(page, per_page=5)
    return render_template('evaluate/evaluation.html', list_=question_list, page=page, kw=kw)

@bp.route('/update/<int:evaluate_id>/',methods=('GET','POST'))
def update(evaluate_id):
    form=RegistForm()
    e = Evaluate.query.get(evaluate_id)
    if request.method == 'POST':
        if form.validate_on_submit():
            e.lec_name=form.lec_name.data
            e.pro_name=form.pro_name.data
            e.lec_skill=form.lec_skill.data
            e.lec_level=form.lec_level.data
            e.content_title=form.content_title.data
            e.eval_contents=form.eval_contents.data
            db.session.commit()
            flash('수정 완료!!!!')
            return redirect(url_for('evaluate.evaluate'))
    return render_template('evaluate/evaluate_update.html', form=form,evaluate_=e)

@bp.route('/detail/<int:evaluate_id>/',methods=('GET','POST'))
def detail(evaluate_id):
    evaluate_ = Evaluate.query.get(evaluate_id)
    return render_template('evaluate/evaulate_detail.html', evaluate_=evaluate_)

@bp.route('/delete/<int:evaluate_id>')
@login_required
def delete(evaluate_id):
    e = Evaluate.query.get_or_404(evaluate_id)
    if g.user.userID != e.writer:
        flash('삭제권한이 없습니다')
        return redirect(url_for('evaluate.evaluate',evaluate_=e))
    db.session.delete(e)
    db.session.commit()
    return redirect(url_for('evaluate.evaluate'))

@bp.route('/register',methods=('GET','POST'))
@login_required
def register():
    form=RegistForm()
    if request.method == 'POST':
        # return 'aaa'
        if form.validate_on_submit(): 
            e = Evaluate(lec_name=form.lec_name.data,
            pro_name=form.pro_name.data,
            lec_skill=form.lec_skill.data,
            lec_level=form.lec_level.data,
            content_title=form.content_title.data,
            eval_contents=form.eval_contents.data,
            writer=g.user.userID)
            db.session.add(e)
            db.session.commit()
            flash('등록 성공!!')
            return redirect(url_for('evaluate.evaluate'))
    return render_template('evaluate/evaluation_insert.html',form=form)

eval_page/app/templates/evaluate/evaluate_update.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">

    <!-- Base css -->
    <link rel="stylesheet" href="{{url_for('static',filename='css/normalize.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/reset.css')}}">

    <!-- page css -->
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">


    <title>이클립스 개인 페이지</title>
</head>

<body>
    <div id="wrap">
        <div id="header">
            {% include 'header.html' %}
        </div>
        <!-- header -->
        <div id="contents-sign">
            <div class="container">
                {% include 'nav.html' %}
            </div>
            <div id="sign">
                <br><br>

                <div style="text-align:center;">
                    <font size="6" color="gray">강의평가</font>
                </div>
                <br><br>
                <form action="{{url_for('evaluate.update',evaluate_id=evaluate_.evalID)}}" method="POST">
                    {{ form.csrf_token }}
                    {% include "form_errors.html" %}
                    <table class="sign-table">
                        <tr>
                            <td id="title">강의명</td>
                            <td><input type="text" value="{{form.lec_name.data or evaluate_.lec_name}}" name="lec_name" maxlength="20"></td>
                            <td id="title">교수명</td>
                            <td><input type="text" value="{{form.pro_name.data or evaluate_.pro_name}}" name="pro_name" maxlength="20"></td>
                        </tr>

                        <tr>
                            <td id="title">강의력</td>
                            <td>
                                <select value="{{form.lec_skill.data or evaluate_.lec_skill}}" name="lec_skill">
		                            <option>A</option>
		                            <option>B</option>
		                            <option>C</option>
		                            <option>D</option>                        
		                        </select>
                            </td>
                            <td id="title">난이도</td>
                            <td>
                                <select value="{{form.lec_level.data or evaluate_.lec_level}}" name="lec_level">
		                            <option>A</option>
		                            <option>B</option>
		                            <option>C</option>
		                            <option>D</option>                        
		                        </select>
                            </td>
                        </tr>

                    </table>
                    <br>
                    <table class="sign-table3">
                        <tr>
                            <td id="title">제목</td>
                            <td><input type="text" size="54.5" name="content_title" value="{{form.content_title.data or evaluate_.content_title}}" /></td>
                        </tr>
                        <tr>
                            <td id="title">내용</td>
                            <td>
                                <textarea name="eval_contents" maxlength="2048" style="height:180px;width:430px;">{{form.eval_contents.data or evaluate_.eval_contents}}</textarea>
                            </td>
                        </tr>
                    </table>
                    <div class="reset_sign" style="text-align:center;">
                        <input type="submit" name="key" value="확인" />
                        <a href="{{url_for('evaluate.evaluate')}}">뒤로가기</a>
                    </div>
                    <div><a style="float: right;" href="{{url_for('evaluate.delete',evaluate_id=evaluate_.evalID)}}">삭제</a></div>
                </form>
            </div>
        </div>
        <!-- contents -->
        <div id="footer">
            <?php include($_SERVER["DOCUMENT_ROOT"].'/include/footer.html');?>

        </div>
    </div>
</body>

</html>

eval_page/app/templates/evaluate/evaluation.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">

    <!-- Base css -->
    <link rel="stylesheet" href="{{url_for('static',filename='css/normalize.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/reset.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <!-- page css -->
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
    <script src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>


    <title>이클립스 개인 페이지</title>
    <script type='text/javascript'>
        $(document).ready(function(){
            $(".page-link").on('click', function() {
                $("#page").val($(this).data("page"));
                $("#searchForm").submit();
            });
            $("#btn_search").on('click', function() {
                $("#kw").val($(".kw").val());
                $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
                $("#searchForm").submit();
            });
        });
    </script>
</head>

<body>
    {%- with messages = get_flashed_messages() %} {% if messages %}
    <script>
        alert('{{ messages|tojson|safe }}');
    </script>
    {% endif %} {% endwith -%}
    <div id="wrap">
        <div id="header">
            {% include 'header.html' %}
        </div>
        <!-- header -->
        <div id="contents-log">
            <div id="cont-nav">
                <div class="container">
                    {% include 'nav.html' %}
                </div>
            </div>
            <div id="cont-cont">
                <div class="ss-cont">
                    <div class="row justify-content-end my-3">
                        <div class="col-4 input-group" style="height: 10px;">
                            <input type="text" class="form-control kw" value="{{ kw or '' }}">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="button" id="btn_search">검색</button>
                            </div>
                            <a class="btn-lec2" href="{{url_for('evaluate.register')}}" style="margin-left:5px;">등록하기</a>

                        </div>
                        <form id="searchForm" method="get" action="{{ url_for('evaluate._list') }}">
                            <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
                            <input type="hidden" id="page" name="page" value="{{ page }}">
                        </form>
                    </div>
                </div>
            </div>
            <!-- card -->

            {% if list_ %} {% for li in list_.items %}
                <div class="card">
                    <a href="{{url_for('evaluate.detail',evaluate_id=li.evalID)}}" style="color: black;">

                    <div class="card-header">
                        <div class="row">
                            <div class="col-left">강의명: {{li.lec_name}}&nbsp;</div>
                            <div class="col-leftt"><small>교수:{{li.pro_name}}</small></div>
                            <div class="col-leftt" style="margin-left:5px;float:right;">작성자: {{li.writer}}&nbsp;</div>
                            <div class="col-leftt" style="color:red;margin-left:5px;float:right;">강의력: {{ li.lec_skill }}</div>
                            <div class="col-leftt" style="color:red;float:right;">난이도: {{ li.lec_level }}</div>
                        </div>

                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                            제목 : {{li.content_title}}
                        </h5>
                        <!-- <div class="col-text-right">
                        <a href="/jungjaeho_free/EvalutionServlet?key=good&key2=<%=evalutionVO.getUserID()%>&key3=<%=evalutionVO.getEvalutionID()%>">수정</a>
                        <a href="/jungjaeho_free/EvalutionServlet?key=del&key2=<%=evalutionVO.getUserID()%>&key3=<%=evalutionVO.getEvalutionID()%>">삭제</a>
                    </div> -->
                        <!-- <div class="row">

                        <div class="col-text-right">
                            <a href="/jungjaeho_free/EvalutionServlet?key=good&key2=<%=evalutionVO.getUserID()%>&key3=<%=evalutionVO.getEvalutionID()%>">수정</a>
                            <a href="/jungjaeho_free/EvalutionServlet?key=del&key2=<%=evalutionVO.getUserID()%>&key3=<%=evalutionVO.getEvalutionID()%>">삭제</a>
                        </div>
                    </div> -->
                    </div>
                </a>
                </div>
             {% endfor %} {% else %} {% endif %}
            <ul class="pagination justify-content-center">
                <!-- 이전페이지 -->
                {% if list_.has_prev %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ list_.prev_num }}" href="#">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
                {% endif %} {% for page_num in list_.iter_pages() %} {% if page_num %} {% if page_num != list_.page %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ page_num }}" href="#">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %} {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
                {% endif %} {% endfor %}
                <!-- 다음페이지 -->
                {% if list_.has_next %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ list_.next_num }}" href="#">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
                {% endif %}
            </ul>
            <!-- 페이징처리 끝 -->

        </div>
        <!-- contents -->
        <!-- <div id="footer">
                {% include 'footer.html' %}
			</div> -->

    </div>
</body>

</html>

eval_page/app/templates/evaluate/evaluation_insert.html

<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
			
			<!-- Base css -->
			<link rel="stylesheet" href="{{url_for('static',filename='css/normalize.css')}}">
			<link rel="stylesheet" href="{{url_for('static',filename='css/reset.css')}}"> 
			
			<!-- page css -->
			<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
			<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
			

			<title>이클립스 개인 페이지</title>
	</head>
	<body>
		<div id="wrap">
			<div id="header">
                {% include 'header.html' %}
			</div>
			<!-- header -->
			<div id="contents-sign">
				<div class="container">
					{% include 'nav.html' %}
				</div>
				<div id="sign">
		        <br><br>
		        
		        <div style="text-align:center;">
		        	<font size="6" color="gray">강의평가 등록</font>
		        </div>
		        <br><br>
		        <form action="{{url_for('evaluate.register')}}" method="POST">
					{{ form.csrf_token }}
					{% include "form_errors.html" %}
		            <table class="sign-table">
		                <tr>
		                    <td id="title">강의명</td>
		                    <td><input type="text" value="{{form.lec_name.data or ''}}" name="lec_name" maxlength="20"></td>
		                    <td id="title">교수명</td>
		                    <td><input type="text" value="{{form.pro_name.data or ''}}" name="pro_name" maxlength="20"></td>
		                </tr>
		                        	                   
		                <tr>
		                    <td id="title">강의력</td>
		                    <td>
		                    	 <select value="{{form.lec_skill.data or ''}}" name="lec_skill">
		                            <option>A</option>
		                            <option>B</option>
		                            <option>C</option>
		                            <option>D</option>                        
		                        </select>
		                    </td>
							<td id="title">난이도</td>
		                    <td>
		                        <select value="{{form.lec_level.data or ''}}" name="lec_level">
		                            <option>A</option>
		                            <option>B</option>
		                            <option>C</option>
		                            <option>D</option>                        
		                        </select>
		                    </td>
		                </tr>
		 		               
		            </table>
		            <br>
		             <table class="sign-table3">
		             	<tr>
		             		<td id="title">제목</td>
		             		<td><input type="text" size="54.5" name="content_title" value="{{form.content_title.data or ''}}"/></td>
		             	</tr>
		                <tr>
		                    <td id="title">내용</td>		                   
		                    <td>
		                        <textarea name="eval_contents" value="{{form.eval_contents.data or ''}}" maxlength="2048" style="height:180px;width:430px;"></textarea>
		                    </td>
		                </tr>
		             </table>
		             <div class="reset_sign" style="text-align:center;">
			           	 <input type="submit" name="key" value="등록" />			        
			           	 <a href="{{url_for('evaluate.evaluate')}}">취소</a>
		            </div>
		        </form>
		   		</div>
			</div>
			<!-- contents -->
			<div id="footer">
			<?php include($_SERVER["DOCUMENT_ROOT"].'/include/footer.html');?>

			</div>
		</div>	
	</body>
</html>

eval_page/app/templates/evaluate/evaulate_detail.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">

    <!-- Base css -->
    <link rel="stylesheet" href="{{url_for('static',filename='css/normalize.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/reset.css')}}">

    <!-- page css -->
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">


    <title>이클립스 개인 페이지</title>
</head>

<body>
    <div id="wrap">
        <div id="header">
            {% include 'header.html' %}
        </div>
        <!-- header -->
        <div id="contents-sign">
            <div class="container">
                {% include 'nav.html' %}
            </div>
            <div id="sign">
                <br><br>

                <div style="text-align:center;">
                    <font size="6" color="gray">강의평가</font>
                </div>
                <br><br>
                <!-- <form action="{{url_for('evaluate.evaluate')}}" method="POST"> -->
                <table class="sign-table">
                    <tr>
                        <td id="title">강의명</td>
                        <td><input type="text" value="{{evaluate_.lec_name}}" name="lec_name" maxlength="20" disabled></td>
                        <td id="title">교수명</td>
                        <td><input type="text" value="{{evaluate_.pro_name}}" name="pro_name" maxlength="20" disabled></td>
                    </tr>

                    <tr>
                        <td id="title">강의력</td>
                        <td>
                            <select value="{{evaluate_.lec_skill}}" disabled name="lec_skill">
		                            <option>A</option>
		                            <option>B</option>
		                            <option>C</option>
		                            <option>D</option>                        
		                        </select>
                        </td>
                        <td id="title">난이도</td>
                        <td>
                            <select value="{{evaluate_.lec_level}}" disabled name="lec_level">
		                            <option>A</option>
		                            <option>B</option>
		                            <option>C</option>
		                            <option>D</option>                        
		                        </select>
                        </td>
                    </tr>

                </table>
                <br>
                <table class="sign-table3">
                    <tr>
                        <td id="title">제목</td>
                        <td><input type="text" size="54.5" disabled name="content_title" value="{{evaluate_.content_title}}" /></td>
                    </tr>
                    <tr>
                        <td id="title">내용</td>
                        <td>
                            <textarea name="eval_contents" disabled maxlength="2048" style="height:180px;width:430px;">{{evaluate_.eval_contents}}</textarea>
                        </td>
                    </tr>
                </table>
                <div class="reset_sign" style="text-align:center;">
                    {% if g.user.userID==evaluate_.writer %}
                    <a href="{{url_for('evaluate.update',evaluate_id=evaluate_.evalID)}}">수정</a> {%else%} {%endif%}
                    <a href="{{url_for('evaluate.evaluate')}}">뒤로가기</a>
                </div>
                <!-- </form> -->
            </div>
        </div>
        <!-- contents -->
        <div id="footer">
            <?php include($_SERVER["DOCUMENT_ROOT"].'/include/footer.html');?>

        </div>
    </div>
</body>

</html>