eval_page/app/views/auth.py
from flask import Blueprint,render_template,url_for, flash, request,session,g
from werkzeug.security import generate_password_hash,check_password_hash
from werkzeug.utils import redirect

from app import db
from ..forms import SignupForm, UserLoginForm, UsermodifyForm
from ..views.evaluate import login_required
from ..models import User
import logging

bp = Blueprint('auth', __name__, url_prefix='/')

@bp.before_app_request
def load_logged_in_user():
    user = session.get('user')
    if user is None:
        g.user = None
    else:
        g.user = User.query.get(user)

@bp.route('/')
def index():
    return render_template('./index.html')

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(userID=form.userID.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.userPasswd, form.userPasswd.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user'] = user.userID
            flash('로그인 성공!!')
            return redirect(url_for('auth.index'))
        flash(error)
    return render_template('page/login.html', form=form)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('auth.index'))

@bp.route('/delete')
@login_required
def delete():
    u = User.query.get_or_404(g.user.userID)
    if g.user == None:
        flash('삭제권한이 없습니다')
        return redirect(url_for('auth.index'))
    db.session.delete(u)
    db.session.commit()
    return redirect(url_for('auth.index'))

@bp.route('/user_update/',methods=('GET','POST'))
@login_required
def user_update():
    form = UsermodifyForm()
    if request.method == 'POST':
            if form.validate_on_submit():
                user = User.query.get(g.user.userID)
                user.userPasswd=generate_password_hash(form.userPasswd.data)
                user.userName=form.userName.data
                user.userSex=form.userSex.data
                db.session.commit()
                flash('회원 정보 수정 완료!!!!')
                return redirect(url_for('auth.index'))
            else:
                flash('수정 에러!')
    return render_template('page/userinfo.html', form=form)

@bp.route('/signup/',methods=('GET','POST'))
def signup():
    form = SignupForm()

    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(userID=form.userID.data).first()
        if not user:
            user = User(userID=form.userID.data,
                        userPasswd=generate_password_hash(form.userPasswd.data),
                        userName=form.userName.data,
                        userSex=form.userSex.data)
            db.session.add(user)
            db.session.commit()
            flash('회원가입 성공!!')
            return redirect(url_for('auth.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    
    return render_template('page/signup.html',form=form)

eval_page/app/templates/footer.html
<br><br><hr>
<div class="container">
	<h4 class="foot">@made by jungjaeho</h4>
</div>

eval_page/app/templates/form_errors.html
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

eval_page/app/templates/header.html
<div class="container">
	<div class="quick-menu">
		{% if g.user %}
			<a>{{ g.user.userID }} 님</a>
			<a href="{{url_for('auth.logout')}}">로그아웃</a>
		{% else %}	
			<a href="{{url_for('auth.login')}}">로그인</a>
		{% endif %}
			<a href="http://www.kpu.ac.kr/index.do?sso=ok" target="_blank">학교홈페이지가기</a>
	</div>
	<div class="title">
		<p>이클래스 개인 페이지</p>
		<h1><a href="http://www.kpu.ac.kr/index.do?sso=ok" target="_blank">www.kpu.ac.kr</a></h1>
	</div>
</div>

eval_page/app/templates/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
				
			<!-- Base css -->
			<link rel="stylesheet" href="{{url_for('static',filename='css/normalize.css')}}">
			<link rel="stylesheet" href="{{url_for('static',filename='css/reset.css')}}"> 
			
			<!-- page css -->
			<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
			<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
			
			<!-- jquery plugin -->
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
			<script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>

			<title>이클립스 개인 페이지</title>
	</head>
	<body>
		{%- with messages = get_flashed_messages() %}
			{% if messages %}
				<script>alert('{{ messages|tojson|safe }}');</script>
			{% endif %}
		{% endwith -%}
		<div id="wrap">
			<div id="header">
                {% include 'header.html' %}
			</div>
			<!-- header -->
			<div id="contents">
				<div id="cont-nav">
                {% include 'nav.html' %}
				</div>
				<div id="cont-tit">
					<div class="container">
						<ul class="slider"> 
							<li><a href="https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=025&aid=0002859889" target="_blank"><img src="{{url_for('static',filename='img/1.png')}}"/></a></li>
                            <li><a href="https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=101&oid=015&aid=0003962104" target="_blank"><img src="{{url_for('static',filename='img/3.png')}}" /></a></li>
                            <li><a href="http://news.unn.net/news/articleView.html?idxno=190871" target="_blank"><img src="{{url_for('static',filename='img/2.png')}}" /></a></li>
							<li><a href="https://www.msn.com/ko-kr/news/national/%ED%95%9C%EA%B5%AD%EC%82%B0%EA%B8%B0%EB%8C%80-%ED%8A%B9%ED%99%94%ED%98%95-%EC%B0%BD%EC%97%85%EC%84%A0%EB%8F%84%EB%8C%80%ED%95%99-%EC%84%A0%EC%A0%95%E2%80%A63%EB%85%84%EA%B0%84-15%EC%96%B5-%EC%A7%80%EC%9B%90/ar-AAy2LTd" target="_blank"><img src="{{url_for('static',filename='img/4.png')}}" /></a></li>
							<li><a href="http://news.kbs.co.kr/news/view.do?ncd=4034085&ref=A" target="_blank"><img src="{{url_for('static',filename='img/5.png')}}" /></a></li>
						</ul>

					</div>
				</div>
				<div id="cont-cont">
					<div class="container">
						<div class="cont">
							<div class="box box1">
								<a href="http://www.kpu.ac.kr/download_file/BK21plus.pdf" target="_blank"><img src="{{url_for('static',filename='img/6.png')}}" /></a>
							</div>
							<div class="box box2">
								<a href="https://startup.kpu.ac.kr/info/view/notice?seq_no=2201" target="_blank"><img src="{{url_for('static',filename='img/7.png')}}"/></a>
							</div>
							<div class="box box3">
								<a href="http://www.ygoon.com/mall/signUp/uniStepOne?affiliateId=524" target="_blank"><img src="{{url_for('static',filename='img/8.png')}}" /></a>
							</div>
							<div class="box box4">
								<a href="http://www.kpu.ac.kr/counseling/index.do" target="_blank"><img src="{{url_for('static',filename='img/9.png')}}" /></a>
							</div>
							<div class="box box5">
								<a href="http://edu.labs.go.kr/MainHome.do?cmd=indexMain" target="_blank"><img src="{{url_for('static',filename='img/10.png')}}" /></a>
							</div>
							<div class="box box6">
								<a href="http://www.academyinfo.go.kr/UIPISA/uipnh/unt/ipsrch/UntUnvAcdtSrchPupExtrn.do?schlId=0000247" target="_blank"><img src="{{url_for('static',filename='img/11.png')}}" /></a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- contents -->
			<div id="footer">
                {% include 'footer.html' %}
			</div>
		</div>
		<!-- wrap -->
    	<script type="text/javascript" src="{{url_for('static',filename='js/imgslide.js')}}"></script>
	</body>
</html>

eval_page/app/templates/nav.html
<div class="container">
	<nav id="Nav-Menu">
		<ul>
			<li><a class="menubar" href="/">메인</a></li>
			<li><a class="menubar" href="{{url_for('evaluate.evaluate')}}">강의평가</a></li>
			<li><a class="menubar" href="{{url_for('auth.user_update')}}">회원정보</a></li>
		</ul>
	</nav> 
</div>